<?php

class ConstrueCountriesTableSeeder extends Seeder {

    public function run()
    {
        $table = 'construe_countries';

        $rows = array(
                        array('id'=>'029', 'name'=>'Caribbean', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AE' , 'name'=>'U.A.E.', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AF' , 'name'=>'Afghanistan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AL' , 'name'=>'Albania', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AM' , 'name'=>'Armenia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AR' , 'name'=>'Argentina', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AT' , 'name'=>'Austria', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AU' , 'name'=>'Australia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'AZ' , 'name'=>'Azerbaijan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BA' , 'name'=>'Bosnia and Herzegovina', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BD' , 'name'=>'Bangladesh', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BE' , 'name'=>'Belgium', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BG' , 'name'=>'Bulgaria', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BH' , 'name'=>'Bahrain', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BN' , 'name'=>'Brunei Darussalam', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BO' , 'name'=>'Bolivia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BR' , 'name'=>'Brazil', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BY' , 'name'=>'Belarus', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'BZ' , 'name'=>'Belize', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CA' , 'name'=>'Canada', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CH' , 'name'=>'Switzerland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CL' , 'name'=>'Chile', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CN' , 'name'=>'People\'s Republic of China', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CO' , 'name'=>'Colombia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CR' , 'name'=>'Costa Rica', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CS' , 'name'=>'Serbia and Montenegro (Former)', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'CZ' , 'name'=>'Czech Republic', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'DE' , 'name'=>'Germany', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'DK' , 'name'=>'Denmark', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'DO' , 'name'=>'Dominican Republic', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'DZ' , 'name'=>'Algeria', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'EC' , 'name'=>'Ecuador', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'EE' , 'name'=>'Estonia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'EG' , 'name'=>'Egypt', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ES' , 'name'=>'Spain', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ET' , 'name'=>'Ethiopia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'FI' , 'name'=>'Finland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'FO' , 'name'=>'Faroe Islands', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'FR' , 'name'=>'France', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'GB' , 'name'=>'United Kingdom', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'GE' , 'name'=>'Georgia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'GL' , 'name'=>'Greenland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'GR' , 'name'=>'Greece', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'GT' , 'name'=>'Guatemala', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'HK' , 'name'=>'Hong Kong S.A.R.', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'HN' , 'name'=>'Honduras', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'HR' , 'name'=>'Croatia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'HU' , 'name'=>'Hungary', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ID' , 'name'=>'Indonesia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IE' , 'name'=>'Ireland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IL' , 'name'=>'Israel', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IN' , 'name'=>'India', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IQ' , 'name'=>'Iraq', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IR' , 'name'=>'Iran', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IS' , 'name'=>'Iceland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'IT' , 'name'=>'Italy', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'JM' , 'name'=>'Jamaica', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'JO' , 'name'=>'Jordan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'JP' , 'name'=>'Japan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KE' , 'name'=>'Kenya', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KG' , 'name'=>'Kyrgyzstan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KH' , 'name'=>'Cambodia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KR' , 'name'=>'Korea', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KW' , 'name'=>'Kuwait', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'KZ' , 'name'=>'Kazakhstan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LA' , 'name'=>'Lao P.D.R.', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LB' , 'name'=>'Lebanon', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LI' , 'name'=>'Liechtenstein', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LK' , 'name'=>'Sri Lanka', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LT' , 'name'=>'Lithuania', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LU' , 'name'=>'Luxembourg', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LV' , 'name'=>'Latvia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'LY' , 'name'=>'Libya', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MA' , 'name'=>'Morocco', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MC' , 'name'=>'Principality of Monaco', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ME' , 'name'=>'Montenegro', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MK' , 'name'=>'Macedonia (FYROM)', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MN' , 'name'=>'Mongolia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MO' , 'name'=>'Macao S.A.R.', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MT' , 'name'=>'Malta', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MV' , 'name'=>'Maldives', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MX' , 'name'=>'Mexico', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'MY' , 'name'=>'Malaysia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NG' , 'name'=>'Nigeria', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NI' , 'name'=>'Nicaragua', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NL' , 'name'=>'Netherlands', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NO' , 'name'=>'Norway', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NP' , 'name'=>'Nepal', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'NZ' , 'name'=>'New Zealand', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'OM' , 'name'=>'Oman', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PA' , 'name'=>'Panama', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PE' , 'name'=>'Peru', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PH' , 'name'=>'Republic of the Philippines', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PK' , 'name'=>'Islamic Republic of Pakistan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PL' , 'name'=>'Poland', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PR' , 'name'=>'Puerto Rico', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PT' , 'name'=>'Portugal', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'PY' , 'name'=>'Paraguay', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'QA' , 'name'=>'Qatar', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'RO' , 'name'=>'Romania', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'RS' , 'name'=>'Serbia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'RU' , 'name'=>'Russia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'RW' , 'name'=>'Rwanda', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SA' , 'name'=>'Saudi Arabia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SE' , 'name'=>'Sweden', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SG' , 'name'=>'Singapore', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SI' , 'name'=>'Slovenia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SK' , 'name'=>'Slovakia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SN' , 'name'=>'Senegal', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SV' , 'name'=>'El Salvador', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'SY' , 'name'=>'Syria', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TH' , 'name'=>'Thailand', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TJ' , 'name'=>'Tajikistan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TM' , 'name'=>'Turkmenistan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TN' , 'name'=>'Tunisia', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TR' , 'name'=>'Turkey', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TT' , 'name'=>'Trinidad and Tobago', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'TW' , 'name'=>'Taiwan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'UA' , 'name'=>'Ukraine', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'US' , 'name'=>'United States', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'UY' , 'name'=>'Uruguay', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'UZ' , 'name'=>'Uzbekistan', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'VE' , 'name'=>'Bolivarian Republic of Venezuela', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'VN' , 'name'=>'Vietnam', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'YE' , 'name'=>'Yemen', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ZA' , 'name'=>'South Africa', 'created_at' => new DateTime, 'updated_at' => new DateTime),
                        array('id'=>'ZW' , 'name'=>'Zimbabwe', 'created_at' => new DateTime, 'updated_at' => new DateTime),
        );

        DB::table($table)->truncate();      
        DB::table($table)->insert($rows);

    }
}
